name: cargo-checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./kls

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        rustup target add wasm32-unknown-unknown

    - name: Build with wasm-pack
      run: wasm-pack build

    - name: Test with wasm-pack
      run: wasm-pack test --headless --firefox

    - name: Lint and Format
      run: |
        rustup component add clippy
        cargo clippy --target wasm32-unknown-unknown
        cargo clippy --target wasm32-unknown-unknown -- -D warnings
        cargo fmt --check

