name: cargo-checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - run: rustup target add wasm32-unknown-unknown

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build with wasm-pack
      run: wasm-pack build

    - name: Lint and Format
      run: |
        rustup component add clippy
        cargo clippy --target wasm32-unknown-unknown --verbose
        cargo clippy --target wasm32-unknown-unknown --verbose -- -D warnings
        cargo fmt --target wasm32-unknown-unknown --check --verbose

    - name: Test with wasm-pack
      run: wasm-pack test --headless --firefox
